# Generated by Django 2.1.7 on 2019-03-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_auto_20190319_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('Exam_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Ex_type', models.CharField(max_length=30)),
                ('Ex_Academic_year', models.CharField(max_length=10)),
                ('Ex_Duration', models.IntegerField()),
                ('Ex_degree', models.IntegerField()),
                ('D_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
    ]
