# Generated by Django 2.1.7 on 2019-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190326_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('Q_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Q_question', models.CharField(max_length=500)),
                ('Q_answer1', models.CharField(max_length=300)),
                ('Q_answer2', models.CharField(max_length=300)),
                ('Q_answer3', models.CharField(max_length=300)),
                ('Q_answer4', models.CharField(max_length=300)),
                ('Q_right_answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='exams',
            name='D_ssn',
        ),
    ]
