# Generated by Django 2.1.7 on 2019-04-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190401_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
