# Generated by Django 2.1.7 on 2019-04-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctor_a_ssn'),
        ('student', '0011_auto_20190401_1641'),
        ('exam', '0004_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_do_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_degree', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('stu_degree', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='D_ssn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='stu_do_exam',
            name='Ex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exams'),
        ),
        migrations.AddField(
            model_name='stu_do_exam',
            name='stu_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
