# Generated by Django 2.1.7 on 2019-04-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190403_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_do_exam',
            name='Ex_id',
        ),
        migrations.RemoveField(
            model_name='stu_do_exam',
            name='stu_ssn',
        ),
        migrations.DeleteModel(
            name='stu_do_exam',
        ),
    ]
