# Generated by Django 2.1.7 on 2019-04-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20190403_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='D_ssn',
        ),
    ]
