# Generated by Django 2.1.7 on 2019-06-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20190623_2025'),
        ('adminstrator', '0004_auto_20190623_2025'),
        ('student', '0014_auto_20190623_2025'),
        ('exam', '0007_remove_exams_d_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_contain_qsi',
            fields=[
                ('Qsi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Question', models.CharField(max_length=500)),
                ('Ans1', models.CharField(max_length=300)),
                ('Ans2', models.CharField(max_length=300)),
                ('Ans3', models.CharField(max_length=300)),
                ('Ans4', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='stu_do_ex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=50)),
                ('Ex_type', models.CharField(max_length=40)),
                ('Total_degree', models.IntegerField()),
                ('Stu_degree', models.IntegerField()),
                ('State', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('Sup_id', models.IntegerField(unique=True)),
                ('Sup_ssn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Sup_name', models.CharField(max_length=50, unique=True)),
                ('Entry_code', models.IntegerField(unique=True)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=80)),
                ('A_ssn', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Administrator')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='D_ssn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='stu_do_ex',
            name='Ex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exams'),
        ),
        migrations.AddField(
            model_name='stu_do_ex',
            name='S_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='ex_contain_qsi',
            name='Ex_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.Exams'),
        ),
    ]
