# Generated by Django 2.1.7 on 2019-06-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20190623_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_do_ex',
            name='S_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
