# Generated by Django 2.1.7 on 2019-06-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20190624_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='Ex_number_of_Q',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='stu_do_ex',
            name='S_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
