# Generated by Django 2.1.7 on 2019-06-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20190624_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex_contain_qsi',
            name='Question_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stu_do_ex',
            name='S_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
