# Generated by Django 2.1.7 on 2019-03-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0002_auto_20190326_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='ID',
            new_name='A_ID',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='name',
            new_name='A_name',
        ),
    ]
