# Generated by Django 2.1.7 on 2019-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_auto_20190326_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='A_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
