# Generated by Django 2.1.7 on 2019-03-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('D_id', models.BigIntegerField(unique=True)),
                ('D_ssn', models.IntegerField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('D_name', models.CharField(max_length=50, unique=True)),
                ('D_phone', models.IntegerField(max_length=12)),
                ('Address', models.CharField(max_length=80)),
                ('A_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Administrator')),
            ],
        ),
    ]
