# Generated by Django 2.1.7 on 2019-03-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190319_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='D_phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='D_department',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='D_faculty',
            field=models.CharField(default=0, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='D_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
