# Generated by Django 2.1.7 on 2019-03-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190326_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Address',
            new_name='D_address',
        ),
    ]
