# Generated by Django 2.1.7 on 2019-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190331_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='D_id',
            field=models.BigIntegerField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='D_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='D_ssn',
            field=models.IntegerField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
