# Generated by Django 2.1.7 on 2019-04-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190401_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='D_ssn',
            field=models.BigIntegerField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
