# Generated by Django 2.1.7 on 2019-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20190401_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='D_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='D_ssn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
