# Generated by Django 2.1.7 on 2019-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190401_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('Q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Q_question', models.CharField(max_length=500)),
                ('Q_answer1', models.CharField(max_length=300)),
                ('Q_answer2', models.CharField(max_length=300)),
                ('Q_answer3', models.CharField(max_length=300)),
                ('Q_answer4', models.CharField(max_length=300)),
                ('Q_right_answer', models.CharField(max_length=300)),
            ],
        ),
    ]
