# Generated by Django 2.1.7 on 2019-04-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctor_a_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='A_ssn',
        ),
    ]
