# Generated by Django 2.1.7 on 2019-06-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0004_auto_20190623_2025'),
        ('doctor', '0012_remove_doctor_a_ssn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='D_department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='D_faculty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='A_ssn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Administrator'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='D_phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
