# Generated by Django 2.1.7 on 2019-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20190623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='D_faculty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
