# Generated by Django 2.1.7 on 2019-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctor_d_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='D_department',
            field=models.CharField(default='', max_length=20),
        ),
    ]
