# Generated by Django 2.1.7 on 2019-06-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_doctor_d_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='D_phone',
        ),
    ]
