# Generated by Django 2.1.7 on 2019-07-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_remove_doctor_d_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=30)),
                ('C_number', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Te_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Te_course', models.CharField(max_length=30)),
                ('Te_Academic_year', models.CharField(max_length=10)),
                ('Tx_degree', models.IntegerField()),
                ('Te_number_of_Q', models.IntegerField(default=None)),
                ('D_ssn', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Test_question',
            fields=[
                ('Qsi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Question', models.CharField(max_length=500)),
                ('Ans1', models.CharField(max_length=300)),
                ('Ans2', models.CharField(max_length=300)),
                ('Ans3', models.CharField(max_length=300)),
                ('Ans4', models.CharField(max_length=300)),
                ('Question_no', models.IntegerField(default=0)),
                ('Right_ans', models.CharField(default=None, max_length=1)),
                ('Te_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.Test')),
            ],
        ),
    ]
