# Generated by Django 2.1.7 on 2019-03-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('ID', models.IntegerField(unique=True)),
                ('A_ssn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_ID', models.IntegerField(unique=True)),
                ('stu_ssn', models.IntegerField(unique=True)),
                ('stu_name', models.CharField(max_length=50)),
                ('academic_year', models.IntegerField()),
                ('stu_phone', models.IntegerField()),
                ('p_phone', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('A_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Administrator')),
            ],
        ),
    ]
