# Generated by Django 2.1.7 on 2019-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_ID',
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_ssn',
            field=models.BigIntegerField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='p_phone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_phone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_ssn',
            field=models.BigIntegerField(unique=True),
        ),
    ]
