# Generated by Django 2.1.7 on 2019-03-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190317_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='A_ssn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='p_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_phone',
            field=models.IntegerField(),
        ),
    ]
