# Generated by Django 2.1.7 on 2019-03-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0001_initial'),
        ('student', '0004_auto_20190319_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='A_ssn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminstrator.Administrator'),
            preserve_default=False,
        ),
    ]
