# Generated by Django 2.1.7 on 2019-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_a_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_ssn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
