# Generated by Django 2.1.7 on 2019-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190319_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='stu_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='p_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_department',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_faculty',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_level_of_study',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
