# Generated by Django 2.1.7 on 2019-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190327_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_level',
            field=models.BigIntegerField(),
        ),
    ]
