# Generated by Django 2.1.7 on 2019-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190331_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.BigIntegerField(max_length=80, unique=True),
        ),
    ]
