# Generated by Django 2.1.7 on 2019-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190401_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
